version: '3.9'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: dsaquel/front-app
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.client.rule=Host(`osutournament.com`)"
        - "traefik.http.routers.client.entrypoints=web"
        - "traefik.http.services.client.loadbalancer.server.port=80"
    networks:
      - api_network

networks:
  api_network:
    external: true
