version: '3.9'

services:
  client:
    build: .
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    external_links:
      - "api_node-app_1:node-app"
    networks:
      - api_network

networks:
  api_network:
    external:
      name: api_network
