version: '3.9'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: dsaquel/front-app
    deploy:
      replicas: 1
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
