version: '3.9'

services:
  client:
    deploy:
      replicas: 1
    build: .
    image: dsaquel/front-app
    ports:
      - '8080:8080'
    networks:
      - api_network

networks:
  api_network:
    name: api_network
    external: true
