// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLayout: typeof import('./components/Ui/Layout/AppLayout.vue')['default']
    BracketMatch: typeof import('./components/tournament/match/BracketMatch.vue')['default']
    CommonDatepicker: typeof import('./components/Common/CommonDatepicker.vue')['default']
    EnProcess: typeof import('./components/EnProcess.md')['default']
    LobbyCreate: typeof import('./components/qualifier/LobbyCreate.vue')['default']
    LobbySetScores: typeof import('./components/qualifier/LobbySetScores.vue')['default']
    LobbySettings: typeof import('./components/qualifier/LobbySettings.vue')['default']
    LowerBracket: typeof import('./components/tournament/bracket/LowerBracket.vue')['default']
    MainLayout: typeof import('./components/Ui/Layout/childs/MainLayout.vue')['default']
    MapCreate: typeof import('./components/tournament/mappool/MapCreate.vue')['default']
    MappoolCreate: typeof import('./components/tournament/mappool/MappoolCreate.vue')['default']
    MappoolSettings: typeof import('./components/tournament/mappool/MappoolSettings.vue')['default']
    MappoolTable: typeof import('./components/tournament/mappool/MappoolTable.vue')['default']
    MapScoreTable: typeof import('./components/qualifier/MapScoreTable.vue')['default']
    MarkdownRender: typeof import('./components/Inputs/MarkdownRender.vue')['default']
    MarkdownTextarea: typeof import('./components/Inputs/MarkdownTextarea.vue')['default']
    MatchDetail: typeof import('./components/tournament/match/MatchDetail.vue')['default']
    NavigationDrawer: typeof import('./components/Ui/Layout/childs/NavigationDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TemplateDraft: typeof import('./components/draft/TemplateDraft.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    ToolbarLayout: typeof import('./components/Ui/Layout/childs/ToolbarLayout.vue')['default']
    TournamentStaff: typeof import('./components/tournament/staff/TournamentStaff.vue')['default']
    UpperBracket: typeof import('./components/tournament/bracket/UpperBracket.vue')['default']
    ZhProcess: typeof import('./components/ZhProcess.md')['default']
  }
}
