// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLayout: typeof import('./components/Ui/Layout/AppLayout.vue')['default']
    AvatarUser: typeof import('./components/avatar/AvatarUser.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EmptyMarkdown: typeof import('./components/Markdown/EmptyMarkdown.md')['default']
    EnProcess: typeof import('./components/EnProcess.md')['default']
    IAkarIconsGithubFill: typeof import('~icons/akar-icons/github-fill')['default']
    ILaLanguage: typeof import('~icons/la/language')['default']
    'IMdi:house': typeof import('~icons/mdi/house')['default']
    'IMdi:loading': typeof import('~icons/mdi/loading')['default']
    'IMdi:tournament': typeof import('~icons/mdi/tournament')['default']
    IMdiContentDuplicate: typeof import('~icons/mdi/content-duplicate')['default']
    IMdiHomeSearchOutline: typeof import('~icons/mdi/home-search-outline')['default']
    IPhCloudMoonBold: typeof import('~icons/ph/cloud-moon-bold')['default']
    IPhSunHorizonBold: typeof import('~icons/ph/sun-horizon-bold')['default']
    IRiArticleLine: typeof import('~icons/ri/article-line')['default']
    MainLayout: typeof import('./components/Ui/Layout/childs/MainLayout.vue')['default']
    MarkdownTextarea: typeof import('./components/Inputs/MarkdownTextarea.vue')['default']
    NavigationDrawer: typeof import('./components/Ui/Layout/childs/NavigationDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Textarea: typeof import('./components/Inputs/Textarea.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    ToolbarLayout: typeof import('./components/Ui/Layout/childs/ToolbarLayout.vue')['default']
    UserAvatar: typeof import('./components/Common/UserAvatar.vue')['default']
    ZhProcess: typeof import('./components/ZhProcess.md')['default']
  }
}
